"""empty message

Revision ID: 4cbe0e177f4e
Revises: None
Create Date: 2015-02-09 03:02:23.959865

"""

# revision identifiers, used by Alembic.
revision = '4cbe0e177f4e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.String(length=80), nullable=True),
                    sa.Column('password', sa.String(length=256), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
    )
    op.create_table('question',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=500), nullable=True),
                    sa.Column('text', sa.Text(length=1000), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(length=1000), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('q_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['q_id'], ['question.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('user')
    ### end Alembic commands ###
