"""empty message

Revision ID: 52b772e157e3
Revises: 4cbe0e177f4e
Create Date: 2015-02-09 03:52:09.524353

"""

# revision identifiers, used by Alembic.
revision = '52b772e157e3'
down_revision = '4cbe0e177f4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('vote', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'vote')
    ### end Alembic commands ###
